version: 2.1

orbs:
  maven: circleci/maven@1.1

workflows:
  maven_test:
    jobs:
      - maven/test:
         command: '-Dprofile=browserstack -Dbrowserstack.user=browserstackuser -Dbrowserstack.key=browserstackkey'