version: 2.1

orbs:
  maven: circleci/maven@1.1

workflows:
  maven_test:
    jobs:
      - maven/test:
         command: 'test -D profile=browserstack -D driverSettings.android.capabilities.browserstack.user=$browserstackuser -D driverSettings.android.capabilities.browserstack.key=$browserstackkey'